// automatically generated by the FlatBuffers compiler, do not modify

package com.tokera.ate.dao.msg;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings({"unused", "return.type.incompatible"})
public final class MessageData extends Table {
  public static MessageData getRootAsMessageData(ByteBuffer _bb) { return getRootAsMessageData(_bb, new MessageData()); }
  public static MessageData getRootAsMessageData(ByteBuffer _bb, MessageData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MessageData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte payload(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int payloadLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public @org.checkerframework.checker.nullness.qual.Nullable ByteBuffer payloadAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public @org.checkerframework.checker.nullness.qual.Nullable ByteBuffer payloadInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public @org.checkerframework.checker.nullness.qual.Nullable MessageDataHeader header() { return header(new MessageDataHeader()); }
  public @org.checkerframework.checker.nullness.qual.Nullable MessageDataHeader header(MessageDataHeader obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public @org.checkerframework.checker.nullness.qual.Nullable MessageDataDigest digest() { return digest(new MessageDataDigest()); }
  public @org.checkerframework.checker.nullness.qual.Nullable MessageDataDigest digest(MessageDataDigest obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createMessageData(FlatBufferBuilder builder,
      int payloadOffset,
      int headerOffset,
      int digestOffset) {
    builder.startObject(3);
    MessageData.addDigest(builder, digestOffset);
    MessageData.addHeader(builder, headerOffset);
    MessageData.addPayload(builder, payloadOffset);
    return MessageData.endMessageData(builder);
  }

  public static void startMessageData(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(0, payloadOffset, 0); }
  public static int createPayloadVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startPayloadVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addHeader(FlatBufferBuilder builder, int headerOffset) { builder.addOffset(1, headerOffset, 0); }
  public static void addDigest(FlatBufferBuilder builder, int digestOffset) { builder.addOffset(2, digestOffset, 0); }
  public static int endMessageData(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

