// automatically generated by the FlatBuffers compiler, do not modify

package com.tokera.ate.dao.msg;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;
import org.checkerframework.checker.nullness.qual.Nullable;

@SuppressWarnings({"unused", "return.type.incompatible"})
public final class MessageEncryptText extends Table {
  public static MessageEncryptText getRootAsMessageEncryptText(ByteBuffer _bb) { return getRootAsMessageEncryptText(_bb, new MessageEncryptText()); }
  public static MessageEncryptText getRootAsMessageEncryptText(ByteBuffer _bb, MessageEncryptText obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MessageEncryptText __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public @Nullable String publicKeyHash() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public @Nullable ByteBuffer publicKeyHashAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public @Nullable ByteBuffer publicKeyHashInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public @Nullable String textHash() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public @Nullable ByteBuffer textHashAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public @Nullable ByteBuffer textHashInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public byte encryptedText(int j) { int o = __offset(8); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int encryptedTextLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public @Nullable ByteBuffer encryptedTextAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public @Nullable ByteBuffer encryptedTextInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createMessageEncryptText(FlatBufferBuilder builder,
      int publicKeyHashOffset,
      int textHashOffset,
      int encryptedTextOffset) {
    builder.startObject(3);
    MessageEncryptText.addEncryptedText(builder, encryptedTextOffset);
    MessageEncryptText.addTextHash(builder, textHashOffset);
    MessageEncryptText.addPublicKeyHash(builder, publicKeyHashOffset);
    return MessageEncryptText.endMessageEncryptText(builder);
  }

  public static void startMessageEncryptText(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addPublicKeyHash(FlatBufferBuilder builder, int publicKeyHashOffset) { builder.addOffset(0, publicKeyHashOffset, 0); }
  public static void addTextHash(FlatBufferBuilder builder, int textHashOffset) { builder.addOffset(1, textHashOffset, 0); }
  public static void addEncryptedText(FlatBufferBuilder builder, int encryptedTextOffset) { builder.addOffset(2, encryptedTextOffset, 0); }
  public static int createEncryptedTextVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startEncryptedTextVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endMessageEncryptText(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

