// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_COM_TOKERA_ATE_DAO_H_
#define FLATBUFFERS_GENERATED_COMMON_COM_TOKERA_ATE_DAO_H_

#include "flatbuffers/flatbuffers.h"

namespace com {
namespace tokera {
namespace ate {
namespace dao {

struct ObjId;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) ObjId FLATBUFFERS_FINAL_CLASS {
 private:
  int64_t low_;
  int64_t high_;

 public:
  ObjId() {
    memset(this, 0, sizeof(ObjId));
  }
  ObjId(int64_t _low, int64_t _high)
      : low_(flatbuffers::EndianScalar(_low)),
        high_(flatbuffers::EndianScalar(_high)) {
  }
  int64_t low() const {
    return flatbuffers::EndianScalar(low_);
  }
  int64_t high() const {
    return flatbuffers::EndianScalar(high_);
  }
};
FLATBUFFERS_STRUCT_END(ObjId, 16);

}  // namespace dao
}  // namespace ate
}  // namespace tokera
}  // namespace com

#endif  // FLATBUFFERS_GENERATED_COMMON_COM_TOKERA_ATE_DAO_H_
