// automatically generated by the FlatBuffers compiler, do not modify

package com.tokera.ate.dao;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings({"argument.type.incompatible", "return.type.incompatible", "dereference.of.nullable", "iterating.over.nullable", "method.invocation.invalid", "override.return.invalid", "unnecessary.equals", "known.nonnull", "flowexpr.parse.error.postcondition", "unboxing.of.nullable", "accessing.nullable", "type.invalid.annotations.on.use", "switching.nullable", "initialization.fields.uninitialized", "unused"})
public final class ObjId extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ObjId __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long low() { return bb.getLong(bb_pos + 0); }
  public long high() { return bb.getLong(bb_pos + 8); }

  public static int createObjId(FlatBufferBuilder builder, long low, long high) {
    builder.prep(8, 16);
    builder.putLong(high);
    builder.putLong(low);
    return builder.offset();
  }
}

