#![allow(dead_code)]

pub const ERR_OK: i32 = 0;
pub const ERR_EPERM: i32 = 1; /* Operation not permitted */
pub const ERR_ENOENT: i32 = 2;
pub const ERR_ESRCH: i32 = 3; /* No such process */
pub const ERR_EINTR: i32 = 4; /* Interrupted system call */
pub const ERR_EIO: i32 = 5; /* I/O error */
pub const ERR_ENXIO: i32 = 6; /* No such device or address */
pub const ERR_E2BIG: i32 = 7; /* Arg list too long */
pub const ERR_ENOEXEC: i32 = 8; /* Exec format error */
pub const ERR_EBADF: i32 = 9; /* Bad file number */
pub const ERR_ECHILD: i32 = 10; /* No child processes */
pub const ERR_EAGAIN: i32 = 11; /* Try again */
pub const ERR_ENOMEM: i32 = 12; /* Out of memory */
pub const ERR_EACCES: i32 = 13; /* Permission denied */
pub const ERR_EFAULT: i32 = 14; /* Bad address */
pub const ERR_ENOTBLK: i32 = 15; /* Block device required */
pub const ERR_EBUSY: i32 = 16; /* Device or resource busy */
pub const ERR_EEXIST: i32 = 17; /* File exists */
pub const ERR_EXDEV: i32 = 18; /* Cross-device link */
pub const ERR_ENODEV: i32 = 19; /* No such device */
pub const ERR_ENOTDIR: i32 = 20; /* Not a directory */
pub const ERR_EISDIR: i32 = 21; /* Is a directory */
pub const ERR_EINVAL: i32 = 22; /* Invalid argument */
pub const ERR_ENFILE: i32 = 23; /* File table overflow */
pub const ERR_EMFILE: i32 = 24; /* Too many open files */
pub const ERR_ENOTTY: i32 = 25; /* Not a typewriter */
pub const ERR_ETXTBSY: i32 = 26; /* Text file busy */
pub const ERR_EFBIG: i32 = 27; /* File too large */
pub const ERR_ENOSPC: i32 = 28; /* No space left on device */
pub const ERR_ESPIPE: i32 = 29; /* Illegal seek */
pub const ERR_EROFS: i32 = 30; /* Read-only file system */
pub const ERR_EMLINK: i32 = 31; /* Too many links */
pub const ERR_EPIPE: i32 = 32; /* Broken pipe */
pub const ERR_EDOM: i32 = 33; /* Math argument out of domain of func */
pub const ERR_ERANGE: i32 = 34; /* Math result not representable */
pub const ERR_EDEADLK: i32 = 35; /* Resource deadlock would occur */
pub const ERR_ENAMETOOLONG: i32 = 36; /* File name too long */
pub const ERR_ENOLCK: i32 = 37; /* No record locks available */
pub const ERR_ENOSYS: i32 = 38; /* Function not implemented */
pub const ERR_ENOTEMPTY: i32 = 39; /* Directory not empty */
pub const ERR_ELOOP: i32 = 40; /* Too many symbolic links encountered */
pub const ERR_EWOULDBLOCK: i32 = ERR_EAGAIN; /* Operation would block */
pub const ERR_ENOMSG: i32 = 42; /* No message of desired type */
pub const ERR_EIDRM: i32 = 43; /* Identifier removed */
pub const ERR_ECHRNG: i32 = 44; /* Channel number out of range */
pub const ERR_EL2NSYNC: i32 = 45; /* Level 2 not synchronized */
pub const ERR_EL3HLT: i32 = 46; /* Level 3 halted */
pub const ERR_EL3RST: i32 = 47; /* Level 3 reset */
pub const ERR_ELNRNG: i32 = 48; /* Link number out of range */
pub const ERR_EUNATCH: i32 = 49; /* Protocol driver not attached */
pub const ERR_ENOCSI: i32 = 50; /* No CSI structure available */
pub const ERR_EL2HLT: i32 = 51; /* Level 2 halted */
pub const ERR_EBADE: i32 = 52; /* Invalid exchange */
pub const ERR_EBADR: i32 = 53; /* Invalid request descriptor */
pub const ERR_EXFULL: i32 = 54; /* Exchange full */
pub const ERR_ENOANO: i32 = 55; /* No anode */
pub const ERR_EBADRQC: i32 = 56; /* Invalid request code */
pub const ERR_EBADSLT: i32 = 57; /* Invalid slot */

pub const ERR_EDEADLOCK: i32 = ERR_EDEADLK;

pub const ERR_EBFONT: i32 = 59; /* Bad font file format */
pub const ERR_ENOSTR: i32 = 60; /* Device not a stream */
pub const ERR_ENODATA: i32 = 61; /* No data available */
pub const ERR_ETIME: i32 = 62; /* Timer expired */
pub const ERR_ENOSR: i32 = 63; /* Out of streams resources */
pub const ERR_ENONET: i32 = 64; /* Machine is not on the network */
pub const ERR_ENOPKG: i32 = 65; /* Package not installed */
pub const ERR_EREMOTE: i32 = 66; /* Object is remote */
pub const ERR_ENOLINK: i32 = 67; /* Link has been severed */
pub const ERR_EADV: i32 = 68; /* Advertise error */
pub const ERR_ESRMNT: i32 = 69; /* Srmount error */
pub const ERR_ECOMM: i32 = 70; /* Communication error on send */
pub const ERR_EPROTO: i32 = 71; /* Protocol error */
pub const ERR_EMULTIHOP: i32 = 72; /* Multihop attempted */
pub const ERR_EDOTDOT: i32 = 73; /* RFS specific error */
pub const ERR_EBADMSG: i32 = 74; /* Not a data message */
pub const ERR_EOVERFLOW: i32 = 75; /* Value too large for defined data type */
pub const ERR_ENOTUNIQ: i32 = 76; /* Name not unique on network */
pub const ERR_EBADFD: i32 = 77; /* File descriptor in bad state */
pub const ERR_EREMCHG: i32 = 78; /* Remote address changed */
pub const ERR_ELIBACC: i32 = 79; /* Can not access a needed shared library */
pub const ERR_ELIBBAD: i32 = 80; /* Accessing a corrupted shared library */
pub const ERR_ELIBSCN: i32 = 81; /* .lib section in a.out corrupted */
pub const ERR_ELIBMAX: i32 = 82; /* Attempting to link in too many shared libraries */
pub const ERR_ELIBEXEC: i32 = 83; /* Cannot exec a shared library directly */
pub const ERR_EILSEQ: i32 = 84; /* Illegal byte sequence */
pub const ERR_ERESTART: i32 = 85; /* Interrupted system call should be restarted */
pub const ERR_ESTRPIPE: i32 = 86; /* Streams pipe error */
pub const ERR_EUSERS: i32 = 87; /* Too many users */
pub const ERR_ENOTSOCK: i32 = 88; /* Socket operation on non-socket */
pub const ERR_EDESTADDRREQ: i32 = 89; /* Destination address required */
pub const ERR_EMSGSIZE: i32 = 90; /* Message too long */
pub const ERR_EPROTOTYPE: i32 = 91; /* Protocol wrong type for socket */
pub const ERR_ENOPROTOOPT: i32 = 92; /* Protocol not available */
pub const ERR_EPROTONOSUPPORT: i32 = 93; /* Protocol not supported */
pub const ERR_ESOCKTNOSUPPORT: i32 = 94; /* Socket type not supported */
pub const ERR_EOPNOTSUPP: i32 = 95; /* Operation not supported on transport endpoint */
pub const ERR_EPFNOSUPPORT: i32 = 96; /* Protocol family not supported */
pub const ERR_EAFNOSUPPORT: i32 = 97; /* Address family not supported by protocol */
pub const ERR_EADDRINUSE: i32 = 98; /* Address already in use */
pub const ERR_EADDRNOTAVAIL: i32 = 99; /* Cannot assign requested address */
pub const ERR_ENETDOWN: i32 = 100; /* Network is down */
pub const ERR_ENETUNREACH: i32 = 101; /* Network is unreachable */
pub const ERR_ENETRESET: i32 = 102; /* Network dropped connection because of reset */
pub const ERR_ECONNABORTED: i32 = 103; /* Software caused connection abort */
pub const ERR_ECONNRESET: i32 = 104; /* Connection reset by peer */
pub const ERR_ENOBUFS: i32 = 105; /* No buffer space available */
pub const ERR_EISCONN: i32 = 106; /* Transport endpoint is already connected */
pub const ERR_ENOTCONN: i32 = 107; /* Transport endpoint is not connected */
pub const ERR_ESHUTDOWN: i32 = 108; /* Cannot send after transport endpoint shutdown */
pub const ERR_ETOOMANYREFS: i32 = 109; /* Too many references: cannot splice */
pub const ERR_ETIMEDOUT: i32 = 110; /* Connection timed out */
pub const ERR_ECONNREFUSED: i32 = 111; /* Connection refused */
pub const ERR_EHOSTDOWN: i32 = 112; /* Host is down */
pub const ERR_EHOSTUNREACH: i32 = 113; /* No route to host */
pub const ERR_EALREADY: i32 = 114; /* Operation already in progress */
pub const ERR_EINPROGRESS: i32 = 115; /* Operation now in progress */
pub const ERR_ESTALE: i32 = 116; /* Stale NFS file handle */
pub const ERR_EUCLEAN: i32 = 117; /* Structure needs cleaning */
pub const ERR_ENOTNAM: i32 = 118; /* Not a XENIX named type file */
pub const ERR_ENAVAIL: i32 = 119; /* No XENIX semaphores available */
pub const ERR_EISNAM: i32 = 120; /* Is a named type file */
pub const ERR_EREMOTEIO: i32 = 121; /* Remote I/O error */
pub const ERR_EDQUOT: i32 = 122; /* Quota exceeded */

pub const ERR_ENOMEDIUM: i32 = 123; /* No medium found */
pub const ERR_EMEDIUMTYPE: i32 = 124; /* Wrong medium type */

pub const ERR_TERMINATED: i32 = 130; /* Process was terminated */
pub const ERR_PANIC: i32 = 99999; /* Process has panicked */

pub fn exit_code_to_message(code: i32) -> &'static str {
    match code {
        ERR_OK => "Ok",
        ERR_EPERM => "Operation not permitted",
        ERR_ENOENT => "No such file or directory",
        ERR_ESRCH => "No such process",
        ERR_EINTR => "Interrupted system call",
        ERR_EIO => "I/O error",
        ERR_ENXIO => "No such device or address",
        ERR_E2BIG => "Arg list too long",
        ERR_ENOEXEC => "Exec format error",
        ERR_EBADF => "Bad file number",
        ERR_ECHILD => "No child processes",
        ERR_EAGAIN => "Try again",
        ERR_ENOMEM => "Out of memory",
        ERR_EACCES => "Permission denied",
        ERR_EFAULT => "Bad address",
        ERR_ENOTBLK => "Block device required",
        ERR_EBUSY => "Device or resource busy",
        ERR_EEXIST => "File exists",
        ERR_EXDEV => "Cross-device link",
        ERR_ENODEV => "No such device",
        ERR_ENOTDIR => "Not a directory",
        ERR_EISDIR => "Is a directory",
        ERR_EINVAL => "Invalid argument",
        ERR_ENFILE => "File table overflow",
        ERR_EMFILE => "Too many open files",
        ERR_ENOTTY => "Not a typewriter",
        ERR_ETXTBSY => "Text file busy",
        ERR_EFBIG => "File too large",
        ERR_ENOSPC => "No space left on device",
        ERR_ESPIPE => "Illegal seek",
        ERR_EROFS => "Read-only file system",
        ERR_EMLINK => "Too many links",
        ERR_EPIPE => "Broken pipe",
        ERR_EDOM => "Math argument out of domain of func",
        ERR_ERANGE => "Math result not representable",
        ERR_EDEADLK => "Resource deadlock would occur",
        ERR_ENAMETOOLONG => "File name too long",
        ERR_ENOLCK => "No record locks available",
        ERR_ENOSYS => "Function not implemented",
        ERR_ENOTEMPTY => "Directory not empty",
        ERR_ELOOP => "Too many symbolic links encountered",
        ERR_ENOMSG => "No message of desired type",
        ERR_EIDRM => "Identifier removed",
        ERR_ECHRNG => "Channel number out of range",
        ERR_EL2NSYNC => "Level 2 not synchronized",
        ERR_EL3HLT => "Level 3 halted",
        ERR_EL3RST => "Level 3 reset",
        ERR_ELNRNG => "Link number out of range",
        ERR_EUNATCH => "Protocol driver not attached",
        ERR_ENOCSI => "No CSI structure available",
        ERR_EL2HLT => "Level 2 halted",
        ERR_EBADE => "Invalid exchange",
        ERR_EBADR => "Invalid request descriptor",
        ERR_EXFULL => "Exchange full",
        ERR_ENOANO => "No anode",
        ERR_EBADRQC => "Invalid request code",
        ERR_EBADSLT => "Invalid slot",
        ERR_EBFONT => "Bad font file format",
        ERR_ENOSTR => "Device not a stream",
        ERR_ENODATA => "No data available",
        ERR_ETIME => "Timer expired",
        ERR_ENOSR => "Out of streams resources",
        ERR_ENONET => "Machine is not on the network",
        ERR_ENOPKG => "Package not installed",
        ERR_EREMOTE => "Object is remote",
        ERR_ENOLINK => "Link has been severed",
        ERR_EADV => "Advertise error",
        ERR_ESRMNT => "Srmount error",
        ERR_ECOMM => "Communication error on send",
        ERR_EPROTO => "Protocol error",
        ERR_EMULTIHOP => "Multihop attempted",
        ERR_EDOTDOT => "RFS specific error",
        ERR_EBADMSG => "Not a data message",
        ERR_EOVERFLOW => "Value too large for defined data type",
        ERR_ENOTUNIQ => "Name not unique on network",
        ERR_EBADFD => "File descriptor in bad state",
        ERR_EREMCHG => "Remote address changed",
        ERR_ELIBACC => "Can not access a needed shared library",
        ERR_ELIBBAD => "Accessing a corrupted shared library",
        ERR_ELIBSCN => ".lib section in a.out corrupted",
        ERR_ELIBMAX => "Attempting to link in too many shared libraries",
        ERR_ELIBEXEC => "Cannot exec a shared library directly",
        ERR_EILSEQ => "Illegal byte sequence",
        ERR_ERESTART => "Interrupted system call should be restarted",
        ERR_ESTRPIPE => "Streams pipe error",
        ERR_EUSERS => "Too many users",
        ERR_ENOTSOCK => "Socket operation on non-socket",
        ERR_EDESTADDRREQ => "Destination address required",
        ERR_EMSGSIZE => "Message too long",
        ERR_EPROTOTYPE => "Protocol wrong type for socket",
        ERR_ENOPROTOOPT => "Protocol not available",
        ERR_EPROTONOSUPPORT => "Protocol not supported",
        ERR_ESOCKTNOSUPPORT => "Socket type not supported",
        ERR_EOPNOTSUPP => "Operation not supported on transport endpoint",
        ERR_EPFNOSUPPORT => "Protocol family not supported",
        ERR_EAFNOSUPPORT => "Address family not supported by protocol",
        ERR_EADDRINUSE => "Address already in use",
        ERR_EADDRNOTAVAIL => "Cannot assign requested address",
        ERR_ENETDOWN => "Network is down",
        ERR_ENETUNREACH => "Network is unreachable",
        ERR_ENETRESET => "Network dropped connection because of reset",
        ERR_ECONNABORTED => "Software caused connection abort",
        ERR_ECONNRESET => "Connection reset by peer",
        ERR_ENOBUFS => "No buffer space available",
        ERR_EISCONN => "Transport endpoint is already connected",
        ERR_ENOTCONN => "Transport endpoint is not connected",
        ERR_ESHUTDOWN => "Cannot send after transport endpoint shutdown",
        ERR_ETOOMANYREFS => "Too many references: cannot splice",
        ERR_ETIMEDOUT => "Connection timed out",
        ERR_ECONNREFUSED => "Connection refused",
        ERR_EHOSTDOWN => "Host is down",
        ERR_EHOSTUNREACH => "No route to host",
        ERR_EALREADY => "Operation already in progress",
        ERR_EINPROGRESS => "Operation now in progress",
        ERR_ESTALE => "Stale NFS file handle",
        ERR_EUCLEAN => "Structure needs cleaning",
        ERR_ENOTNAM => "Not a XENIX named type file",
        ERR_ENAVAIL => "No XENIX semaphores available",
        ERR_EISNAM => "Is a named type file",
        ERR_EREMOTEIO => "Remote I/O error",
        ERR_EDQUOT => "Quota exceeded",
        ERR_ENOMEDIUM => "No medium found",
        ERR_EMEDIUMTYPE => "Wrong medium type",
        ERR_PANIC => "Process has panicked",
        ERR_TERMINATED => "Process was terminated",
        _ => "Unknown error",
    }
}
