// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_KEY_COM_TOKERA_ATE_DAO_MSG_H_
#define FLATBUFFERS_GENERATED_KEY_COM_TOKERA_ATE_DAO_MSG_H_

#include "flatbuffers/flatbuffers.h"

namespace com {
namespace tokera {
namespace ate {
namespace dao {
namespace msg {

struct MessagePublicKey;

struct MessagePrivateKey;

struct MessagePublicKey FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PUBLICKEYHASH = 4,
    VT_PUBLICKEY = 6,
    VT_ALIAS = 8
  };
  const flatbuffers::String *publicKeyHash() const {
    return GetPointer<const flatbuffers::String *>(VT_PUBLICKEYHASH);
  }
  const flatbuffers::Vector<int8_t> *publicKey() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_PUBLICKEY);
  }
  const flatbuffers::String *alias() const {
    return GetPointer<const flatbuffers::String *>(VT_ALIAS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PUBLICKEYHASH) &&
           verifier.VerifyString(publicKeyHash()) &&
           VerifyOffset(verifier, VT_PUBLICKEY) &&
           verifier.VerifyVector(publicKey()) &&
           VerifyOffset(verifier, VT_ALIAS) &&
           verifier.VerifyString(alias()) &&
           verifier.EndTable();
  }
};

struct MessagePublicKeyBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_publicKeyHash(flatbuffers::Offset<flatbuffers::String> publicKeyHash) {
    fbb_.AddOffset(MessagePublicKey::VT_PUBLICKEYHASH, publicKeyHash);
  }
  void add_publicKey(flatbuffers::Offset<flatbuffers::Vector<int8_t>> publicKey) {
    fbb_.AddOffset(MessagePublicKey::VT_PUBLICKEY, publicKey);
  }
  void add_alias(flatbuffers::Offset<flatbuffers::String> alias) {
    fbb_.AddOffset(MessagePublicKey::VT_ALIAS, alias);
  }
  explicit MessagePublicKeyBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MessagePublicKeyBuilder &operator=(const MessagePublicKeyBuilder &);
  flatbuffers::Offset<MessagePublicKey> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MessagePublicKey>(end);
    return o;
  }
};

inline flatbuffers::Offset<MessagePublicKey> CreateMessagePublicKey(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> publicKeyHash = 0,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> publicKey = 0,
    flatbuffers::Offset<flatbuffers::String> alias = 0) {
  MessagePublicKeyBuilder builder_(_fbb);
  builder_.add_alias(alias);
  builder_.add_publicKey(publicKey);
  builder_.add_publicKeyHash(publicKeyHash);
  return builder_.Finish();
}

inline flatbuffers::Offset<MessagePublicKey> CreateMessagePublicKeyDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *publicKeyHash = nullptr,
    const std::vector<int8_t> *publicKey = nullptr,
    const char *alias = nullptr) {
  return com::tokera::ate::dao::msg::CreateMessagePublicKey(
      _fbb,
      publicKeyHash ? _fbb.CreateString(publicKeyHash) : 0,
      publicKey ? _fbb.CreateVector<int8_t>(*publicKey) : 0,
      alias ? _fbb.CreateString(alias) : 0);
}

struct MessagePrivateKey FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PRIVATEKEYHASH = 4,
    VT_PRIVATEKEY = 6,
    VT_PUBLICKEY = 8
  };
  const flatbuffers::String *privateKeyHash() const {
    return GetPointer<const flatbuffers::String *>(VT_PRIVATEKEYHASH);
  }
  const flatbuffers::Vector<int8_t> *privateKey() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_PRIVATEKEY);
  }
  const MessagePublicKey *publicKey() const {
    return GetPointer<const MessagePublicKey *>(VT_PUBLICKEY);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PRIVATEKEYHASH) &&
           verifier.VerifyString(privateKeyHash()) &&
           VerifyOffset(verifier, VT_PRIVATEKEY) &&
           verifier.VerifyVector(privateKey()) &&
           VerifyOffset(verifier, VT_PUBLICKEY) &&
           verifier.VerifyTable(publicKey()) &&
           verifier.EndTable();
  }
};

struct MessagePrivateKeyBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_privateKeyHash(flatbuffers::Offset<flatbuffers::String> privateKeyHash) {
    fbb_.AddOffset(MessagePrivateKey::VT_PRIVATEKEYHASH, privateKeyHash);
  }
  void add_privateKey(flatbuffers::Offset<flatbuffers::Vector<int8_t>> privateKey) {
    fbb_.AddOffset(MessagePrivateKey::VT_PRIVATEKEY, privateKey);
  }
  void add_publicKey(flatbuffers::Offset<MessagePublicKey> publicKey) {
    fbb_.AddOffset(MessagePrivateKey::VT_PUBLICKEY, publicKey);
  }
  explicit MessagePrivateKeyBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MessagePrivateKeyBuilder &operator=(const MessagePrivateKeyBuilder &);
  flatbuffers::Offset<MessagePrivateKey> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MessagePrivateKey>(end);
    return o;
  }
};

inline flatbuffers::Offset<MessagePrivateKey> CreateMessagePrivateKey(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> privateKeyHash = 0,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> privateKey = 0,
    flatbuffers::Offset<MessagePublicKey> publicKey = 0) {
  MessagePrivateKeyBuilder builder_(_fbb);
  builder_.add_publicKey(publicKey);
  builder_.add_privateKey(privateKey);
  builder_.add_privateKeyHash(privateKeyHash);
  return builder_.Finish();
}

inline flatbuffers::Offset<MessagePrivateKey> CreateMessagePrivateKeyDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *privateKeyHash = nullptr,
    const std::vector<int8_t> *privateKey = nullptr,
    flatbuffers::Offset<MessagePublicKey> publicKey = 0) {
  return com::tokera::ate::dao::msg::CreateMessagePrivateKey(
      _fbb,
      privateKeyHash ? _fbb.CreateString(privateKeyHash) : 0,
      privateKey ? _fbb.CreateVector<int8_t>(*privateKey) : 0,
      publicKey);
}

}  // namespace msg
}  // namespace dao
}  // namespace ate
}  // namespace tokera
}  // namespace com

#endif  // FLATBUFFERS_GENERATED_KEY_COM_TOKERA_ATE_DAO_MSG_H_
