// automatically generated by the FlatBuffers compiler, do not modify

package com.tokera.ate.dao.msg;

public final class MessageKeyType {
  private MessageKeyType() { }
  public static final short unknown = 0;
  public static final short ntru = 1;
  public static final short ntru_sign = 2;
  public static final short qtesla = 3;
  public static final short newhope = 4;
  public static final short xmss = 5;
  public static final short xmssmt = 6;

  public static final String[] names = { "unknown", "ntru", "ntru_sign", "qtesla", "newhope", "xmss", "xmssmt", };

  public static String name(int e) { return names[e]; }
}

