// automatically generated by the FlatBuffers compiler, do not modify

package com.tokera.ate.dao.msg;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings({"unused", "return.type.incompatible"})
public final class MessageSecurityCastle extends Table {
  public static MessageSecurityCastle getRootAsMessageSecurityCastle(ByteBuffer _bb) { return getRootAsMessageSecurityCastle(_bb, new MessageSecurityCastle()); }
  public static MessageSecurityCastle getRootAsMessageSecurityCastle(ByteBuffer _bb, MessageSecurityCastle obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MessageSecurityCastle __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.tokera.ate.dao.ObjId id() { return id(new com.tokera.ate.dao.ObjId()); }
  public com.tokera.ate.dao.ObjId id(com.tokera.ate.dao.ObjId obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public MessageSecurityGate gates(int j) { return gates(new MessageSecurityGate(), j); }
  public MessageSecurityGate gates(MessageSecurityGate obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int gatesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static void startMessageSecurityCastle(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addStruct(0, idOffset, 0); }
  public static void addGates(FlatBufferBuilder builder, int gatesOffset) { builder.addOffset(1, gatesOffset, 0); }
  public static int createGatesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startGatesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMessageSecurityCastle(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

