// automatically generated by the FlatBuffers compiler, do not modify

package com.tokera.ate.dao.msg;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;
import org.checkerframework.checker.nullness.qual.Nullable;

@SuppressWarnings({"unused", "return.type.incompatible"})
public final class MessagePublicKey extends Table {
  public static MessagePublicKey getRootAsMessagePublicKey(ByteBuffer _bb) { return getRootAsMessagePublicKey(_bb, new MessagePublicKey()); }
  public static MessagePublicKey getRootAsMessagePublicKey(ByteBuffer _bb, MessagePublicKey obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MessagePublicKey __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public @Nullable String publicKeyHash() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public @Nullable ByteBuffer publicKeyHashAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public @Nullable ByteBuffer publicKeyHashInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public byte publicKey(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int publicKeyLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public @Nullable ByteBuffer publicKeyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public @Nullable ByteBuffer publicKeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public @Nullable String alias() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public @Nullable ByteBuffer aliasAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public @Nullable ByteBuffer aliasInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createMessagePublicKey(FlatBufferBuilder builder,
      int publicKeyHashOffset,
      int publicKeyOffset,
      int aliasOffset) {
    builder.startObject(3);
    MessagePublicKey.addAlias(builder, aliasOffset);
    MessagePublicKey.addPublicKey(builder, publicKeyOffset);
    MessagePublicKey.addPublicKeyHash(builder, publicKeyHashOffset);
    return MessagePublicKey.endMessagePublicKey(builder);
  }

  public static void startMessagePublicKey(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addPublicKeyHash(FlatBufferBuilder builder, int publicKeyHashOffset) { builder.addOffset(0, publicKeyHashOffset, 0); }
  public static void addPublicKey(FlatBufferBuilder builder, int publicKeyOffset) { builder.addOffset(1, publicKeyOffset, 0); }
  public static int createPublicKeyVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startPublicKeyVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addAlias(FlatBufferBuilder builder, int aliasOffset) { builder.addOffset(2, aliasOffset, 0); }
  public static int endMessagePublicKey(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

