// automatically generated by the FlatBuffers compiler, do not modify

package com.tokera.ate.dao.msg;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings({"unused", "return.type.incompatible"})
public final class MessageSecurityGate extends Table {
  public static MessageSecurityGate getRootAsMessageSecurityGate(ByteBuffer _bb) { return getRootAsMessageSecurityGate(_bb, new MessageSecurityGate()); }
  public static MessageSecurityGate getRootAsMessageSecurityGate(ByteBuffer _bb, MessageSecurityGate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MessageSecurityGate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public @org.checkerframework.checker.nullness.qual.Nullable String publicKeyHash() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public @org.checkerframework.checker.nullness.qual.Nullable ByteBuffer publicKeyHashAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public @org.checkerframework.checker.nullness.qual.Nullable ByteBuffer publicKeyHashInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public byte encryptedText(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int encryptedTextLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public @org.checkerframework.checker.nullness.qual.Nullable ByteBuffer encryptedTextAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public @org.checkerframework.checker.nullness.qual.Nullable ByteBuffer encryptedTextInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createMessageSecurityGate(FlatBufferBuilder builder,
      int publicKeyHashOffset,
      int encryptedTextOffset) {
    builder.startObject(2);
    MessageSecurityGate.addEncryptedText(builder, encryptedTextOffset);
    MessageSecurityGate.addPublicKeyHash(builder, publicKeyHashOffset);
    return MessageSecurityGate.endMessageSecurityGate(builder);
  }

  public static void startMessageSecurityGate(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addPublicKeyHash(FlatBufferBuilder builder, int publicKeyHashOffset) { builder.addOffset(0, publicKeyHashOffset, 0); }
  public static void addEncryptedText(FlatBufferBuilder builder, int encryptedTextOffset) { builder.addOffset(1, encryptedTextOffset, 0); }
  public static int createEncryptedTextVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startEncryptedTextVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endMessageSecurityGate(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

