// automatically generated by the FlatBuffers compiler, do not modify

package com.tokera.ate.dao.msg;

public final class MessageKeyType {
  private MessageKeyType() { }
  public static final int unknown = 0;
  public static final int ntru = 1;
  public static final int ntru_sign = 2;
  public static final int qtesla = 3;
  public static final int newhope = 4;
  public static final int xmss = 5;
  public static final int xmssmt = 6;

  public static final String[] names = { "unknown", "ntru", "ntru_sign", "qtesla", "newhope", "xmss", "xmssmt", };

  public static String name(int e) { return names[e]; }
}

